offline_camera_calibration:
  ros__parameters:

    minimum_valid_images: 21

    chessboard_size: [7, 9]
    square_size: 30.0 # mm

    image_size: [1024, 1024] # (width, height)
    
    images_path: /home/marco/xarm_devel/src/AA_Resources_Calibration/dlr_stereo_calibration/rescaled_1024/right/
    calibration_path: /home/marco/xarm_devel/src/AA_Resources_Calibration/dlr_stereo_calibration/rescaled_1024/

    calibration_file: calib_cam_right.xml