camera_acquisition:
  ros__parameters:

    number_of_images_to_save: 100

    subscribers:
      camera: /camera/raw_frame

    auto_capture:
      mode: True            # Capture an image every
      time_for_frame: 2.0   # sec
    
    images_path: /home/marco/xarm_devel/src/dependencies/basler_camera/calibration_images/
