offline_camera_calibration:
  ros__parameters:

    minimum_valid_images: 21

    chessboard_size: [7, 9]
    square_size: 30.0 # mm

    image_size: [512, 512] # (width, height)
    
    images_path: /home/marco/erossp_ros2_devel/src/EROSSP_Pose_Estimation/dlr_new_calibration/right/
    calibration_path: /home/marco/erossp_ros2_devel/src/EROSSP_Pose_Estimation/dlr_new_calibration/output_calibration/

    calibration_file: calib_cam_right.xml